#Drone CI File!
#Commit Message: Drone! Captain Canary is here!!     
    
pipeline:
  build:
    image: maven:3.3-jdk-8   
#     secrets: [ ARTIFACTORY_PASSWORD, ARTIFACTORY_USER, ARTIFACTORY_URL, REPOSITORY_KEY ]
    commands:
    # Download the JFrog CLI 
      - curl -fL https://getcli.jfrog.io | sh
#       - ./jfrog config add --artifactory-url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD --interactive=false
#       - ./jfrog c show
    #build
      - mvn package
#       - ls -R
    # Publish the build with bp command
      - ./jfrog config add --artifactory-url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD --interactive=false
      - ./jfrog rt u --user=saravanan060394@gmail.com --password=Muthusam8@123 --url=https://harnesssample.jfrog.io/artifactory/java-generic-local/ "/drone/src/github.com/sarvan060394/Javaapp/target/*.war" "java-generic-local/"
      - ./jfrog rt bp --build-name=javabuild --build-number=1  

