#Drone CI File!
#Commit Message: Drone! Captain Canary is here!! 

# kind: pipeline
# type: docker
# name: default

# steps:
# - name: build
#   image: maven:3.3-jdk-8
#   commands:
#   - mvn compile
# - name: publish  
#   image: plugins/docker
#   settings:
#     username:
#       from_secret: saravanan060394@gmail.com
#     password:
#       from_secret: Muthusam8@123
#     repo: https://harnesssample.jfrog.io/artifactory/java-generic-local/
#     auto_tag: true
#     auto_tag_suffix: drone-build
    
    
pipeline:
#   build:
#     image: maven:3.3-jdk-8
#     commands:
#       - mvn compile
  build:
    image: node:16-alpine3.11
    commands:
      - yum -y update && yum -y install make
      - make install
      - make test
    docker:
    image: plugins/docker
    repo: athieriot/drone-artifactory
    tag: latest
    secrets: [ sarvan060394/dronetest, Muthusam8@123 ]
    when:
      event: push
      branch: master
      local: false

plugin:
  name: Artifactory
  desc: Publish files and artifacts to Artifactory
  type: publish
  image: athieriot/drone-artifactory
  labels:
    - artifactory
#   artifactory:
#     image: athieriot/drone-artifactory
#     url: https://harnesssample.jfrog.io/artifactory/
#     username: saravanan060394@gmail.com
#     password: Muthusam8@123
#     pom: pom.xml
#     files:
#       - target/classes
#       - target/jacoco*
#       - target/*.jar
#       - target/*.war

