#Drone CI File!
#Commit Message: Drone! Captain Canary is here!!     
    
pipeline:
  build:
    image: maven:3.3-jdk-8   
#     secrets: [ ARTIFACTORY_PASSWORD, ARTIFACTORY_USER, ARTIFACTORY_URL, REPOSITORY_KEY ]
    commands:
    # Download the JFrog CLI 
      - curl -fL https://getcli.jfrog.io | sh
      - ./jfrog config add --artifactory-url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD --interactive=false
      - ./jfrog c show
    #build
      - mvn compile
    # Publish the build with bp command
      - ./jfrog rt u ./target/*.war --url=https://harnesssample.jfrog.io/artifactory/java-generic-local/

